csv_log_future_planner:
  _target_: offline_evaluation.planners.csv_log_future_planner.CSVLogFuturePlanner
  _convert_: 'all'
  # CSV file path - use sample trajectories by default
  csv_file_path: "/home/chen/nuplan-devkit/offline_evaluation/data/sample_trajectories.csv"
  # Trajectory parameters (same as log_future_planner) 
  num_poses: 16
  future_time_horizon: 8.0
  # CSV format parameters
  scenario_id_column: "scenario_id"
  trajectory_column_prefix: "ego_"