# nuPlan Planner Benchmark Configuration
# This configuration runs multiple planners on a subset of scenarios for comparison

hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra
  searchpath:
    - pkg://nuplan.planning.script.config.common
    - pkg://nuplan.planning.script.experiments

defaults:
  - default_experiment
  - default_common
  - default_submission
  - simulation_metric:
      - default_metrics
  - callback:
      - simulation_log_callback
  - main_callback:
      - time_callback
      - metric_file_callback
      - metric_aggregator_callback
      - metric_summary_callback
  - splitter: nuplan
  - observation: box_observation
  - ego_controller: perfect_tracking_controller
  - simulation_time_controller: step_simulation_time_controller
  - metric_aggregator:
      - default_weighted_average
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

experiment_name: 'planner_benchmark'
aggregated_metric_folder_name: 'aggregator_metric'
aggregator_save_path: ${output_dir}/${aggregated_metric_folder_name}

# Use mini dataset scenarios for quick benchmarking
scenario_builder: nuplan_mini
scenario_filter: simple_test_scenarios

# Database and map paths
data_loader:
  data_dir: "/home/chen/nuplan-devkit/data/cache/mini"
  map_dir: "/home/chen/nuplan-devkit/maps"

# Output directory for benchmark results
output_dir: "/home/chen/nuplan-devkit/planner_benchmark/results"

# Simulation settings
enable_simulation_progress_bar: True
simulation_history_buffer_duration: 2.0
number_of_gpus_allocated_per_simulation: 0
number_of_cpus_allocated_per_simulation: 1
run_metric: true
exit_on_failure: false
max_callback_workers: 4
disable_callback_parallelization: true
distributed_mode: 'SINGLE_NODE'

# Worker settings
worker: sequential

# Random seed for reproducibility
seed: 42